apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-app
  labels:
    app: flow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-app
  template:
    metadata:
      labels:
        app: flow-app
    spec:
      containers:
      - name: flow-frontend
        image: tharunbabu/flow-ui
        ports:
        - containerPort: 3000
