apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 32000
  selector:
    app: flow-app
  type: NodePort